# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.8.2

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - apt-get update && apt-get install -y libgeos++-dev libproj-dev
          - python -m pip install --upgrade pip
          - pip install poetry
          - poetry install
          - poetry run ./test.sh
