# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.8.2

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          # Need to build geos & proj from source as cartopy needs
          # more recent versions than are available through:
          # apt-get install -y libgeos-dev libproj-dev  :-(
          - apt-get update && apt-get install -y cmake
          - wget http://download.osgeo.org/geos/geos-3.10.1.tar.bz2
          - tar xvf geos-3.10.1.tar.bz2
          - cd geos-3.10.1 && pwd
          - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
          - make && make install
          - wget https://download.osgeo.org/proj/proj-8.1.0.tar.gz
          - tar xvzf proj-8.1.0.tar.gz
          - cd proj-8.1.0 && pwd && ./configure
          - make && make install
          - python -m pip install --upgrade pip
          - pip install poetry
          - poetry install
          - poetry run ./test.sh
