version: "3.4"

# Env variables required in .env, e.g. for Mac:
# M3_VOL=/Volumes/M3
# AUVCTD_VOL=/Volumes/AUVCTD
# WORK_VOL=/opt/docker_auv-python_vols/data

# Required in shell environment:
# export DOCKER_USER_ID=$(id -u)

services:
  auvpython:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - DOCKER_USER_ID=$DOCKER_USER_ID
    image: auvpython_production
    volumes:
      - ${WORK_VOL}:/data
      - ${M3_VOL}:/Volumes/M3:z
      - ${AUVCTD_VOL}:/Volumes/AUVCTD:z
