version: "3.4"

# Env variables required in .env, e.g. for Mac
# M3_VOL=/Volumes/M3
# AUVCTD_VOL=/Volumes/AUVCTD

services:
  auvpython:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - DOCKER_USER_ID=$DOCKER_USER_ID
    image: auvpython_production
    volumes:
      - ${M3_VOL}:/Volumes/M3:z
      - ${AUVCTD_VOL}:/Volumes/AUVCTD:z
