[tool.poetry]
name = "auv-python"
version = "0.1.0"
description = "Python code for processing MBARI Dorado-class AUV instrument data"

license = "MIT"

authors = [
    "Mike McCann <mccann@mbari.org>"
]

readme = 'README.md'  # Markdown files are supported

repository = "https://bitbucket.org/mbari/auv-python"
homepage = "https://bitbucket.org/mbari/auv-python"

keywords = ['auv', 'dorado', 'oceanograpy', 'dataprocessing']

[tool.poetry.dependencies]
# On mac: brew install python@3.11 and update PATH in .zshrc, also had to
# pip uninstall xattr && pip install xattr, see:
# https://github.com/python-poetry/poetry/issues/6891#issuecomment-1343047469
python = "^3.10"  # Compatible python versions must be declared here
toml = "^0.9"
# Dependencies with extras
requests = { version = "^2.23" }
aiohttp = "^3.7.4"
altair = "^4.1.0"
cf-xarray = "^0.6.1"
coards = "^1.0.5"
hvplot = "^0.7.3"
ipywidgets = "^7.6.5"
matplotlib = "^3.4.3"
mkdocs = "^1.2.3"
nc-time-axis = "^1.3.1"
netCDF4 = "^1.5.7"
numpy = "^1.21.2"
pytest = "^6.2.5"
scipy = "^1.7.1"
seawater = "^3.3.4"
xarray = "^0.19.0"
black = "^22.3.0"
bokeh = "^2.4.1"
PyQt5 = "^5.15.6"
ipympl = "^0.9.1"
GitPython = "^3.1.29"
pyarrow = "^10.0.1"


[tool.poetry.dev-dependencies]
pytest = "^6.0"
pytest-cov = "^3.0"
