[tool.poetry]
name = "auv-python"
version = "0.1.0"
description = "Python code for processing MBARI Dorado-class AUV instrument data"

license = "MIT"

authors = [
    "Mike McCann <mccann@mbari.org>"
]

readme = 'README.md'  # Markdown files are supported

repository = "https://bitbucket.org/mbari/auv-python"
homepage = "https://bitbucket.org/mbari/auv-python"

keywords = ['auv', 'dorado', 'oceanograpy', 'dataprocessing']

[tool.poetry.dependencies]
# On mac: brew install python@3.11 and update PATH in .zshrc, also had to
# pip uninstall xattr && pip install xattr, see:
# https://github.com/python-poetry/poetry/issues/6891#issuecomment-1343047469
python = "^3.10"
toml = "^0.9"
# Dependencies with extras
aiohttp = "^3.7.4"
altair = "^4.1.0"
cf-xarray = "^0.8.4"
coards = "^1.0.5"
hvplot = "^0.9.0"
mkdocs = "^1.2.3"
nc-time-axis = "^1.3.1"
netCDF4 = "^1.5.7"
pytest = "^6.2.5"
seawater = "^3.3.4"
black = "^22.3.0"
ipympl = "^0.9.1"
GitPython = "^3.1.29"
pyarrow = "^10.0.1"
datashader = "^0.15.2"
rolling = "^0.3.0"
pysolar = "^0.10"
pooch = "^1.7.0"
statsmodels = "^0.13.5"
pyproj = "^3.5.0"
jupyter = "^1.0.0"
cmocean = "^3.0.3"


[tool.poetry.dev-dependencies]
pytest = "^6.0"
pytest-cov = "^3.0"
