name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Changed from '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.11"

      - name: Install dev dependencies
        run: uv pip install --system .[dev]

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.11"

      - name: Install dependencies
        run: uv pip install --system .

      - name: Set environment variables
        run: |
          echo "BASE_PATH=$HOME/auv_data" >> $GITHUB_ENV
          echo "CAL_DIR=$HOME/auv_data" >> $GITHUB_ENV

      - name: Download and unzip required data files
        run: |
          mkdir -p "$HOME/auv_data"
          wget -q --no-check-certificate -O "$HOME/auv_data/Dorado389.tar.gz" https://stoqs.mbari.org/auv_data/Dorado389.tar.gz
          tar -xvf "$HOME/auv_data/Dorado389.tar.gz" -C "$HOME/auv_data" 2> /dev/null
          wget -q --no-check-certificate -O "$HOME/auv_data/i2map.tar.gz" https://stoqs.mbari.org/auv_data/i2map.tar.gz
          tar -xf "$HOME/auv_data/i2map.tar.gz" -C "$HOME/auv_data" 2> /dev/null
          wget -q --no-check-certificate -O "$HOME/auv_data/SBE-43.tar.gz" https://stoqs.mbari.org/auv_data/SBE-43.tar.gz
          tar -xf "$HOME/auv_data/SBE-43.tar.gz" -C "$HOME/auv_data" 2> /dev/null

      - name: Install pytest
        run: uv pip install --system pytest

      - name: Run tests
        run: pytest
